import postgres from "postgres";

const connectionString =
  process.env.DATABASE_URL ||
  process.env.POSTGRES_URL ||
  process.env.NEON_DATABASE_URL ||
  "";

declare global {
  var qiningSql: ReturnType<typeof postgres> | undefined;
  var qiningSchemaReady: Promise<void> | undefined;
}

export function hasDatabase() {
  return Boolean(connectionString);
}

export function getDatabase() {
  if (!connectionString) {
    throw new Error("DATABASE_URL is not configured");
  }

  if (!globalThis.qiningSql) {
    globalThis.qiningSql = postgres(connectionString, {
      max: 1,
      idle_timeout: 20,
      connect_timeout: 15,
      prepare: false,
    });
  }

  return globalThis.qiningSql;
}

export function ensureDatabase() {
  if (!globalThis.qiningSchemaReady) {
    globalThis.qiningSchemaReady = createSchema().catch((error) => {
      globalThis.qiningSchemaReady = undefined;
      throw error;
    });
  }
  return globalThis.qiningSchemaReady;
}

async function createSchema() {
  const sql = getDatabase();

  await sql`
    CREATE TABLE IF NOT EXISTS posts (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      slug TEXT NOT NULL UNIQUE,
      description TEXT NOT NULL DEFAULT '',
      content TEXT NOT NULL DEFAULT '',
      cover TEXT NOT NULL DEFAULT '',
      category TEXT NOT NULL DEFAULT '',
      tags TEXT[] NOT NULL DEFAULT '{}',
      status TEXT NOT NULL DEFAULT 'draft',
      is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
      views INTEGER NOT NULL DEFAULT 0,
      likes INTEGER NOT NULL DEFAULT 0,
      word_count INTEGER NOT NULL DEFAULT 0,
      reading_time INTEGER NOT NULL DEFAULT 1,
      published_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS chatters (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      content TEXT NOT NULL,
      images TEXT[] NOT NULL DEFAULT '{}',
      mood TEXT NOT NULL DEFAULT '',
      likes INTEGER NOT NULL DEFAULT 0,
      comments_count INTEGER NOT NULL DEFAULT 0,
      status TEXT NOT NULL DEFAULT 'published',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS projects (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      slug TEXT NOT NULL UNIQUE,
      description TEXT NOT NULL DEFAULT '',
      long_description TEXT NOT NULL DEFAULT '',
      cover_image TEXT NOT NULL DEFAULT '',
      tech_stack TEXT[] NOT NULL DEFAULT '{}',
      link_github TEXT NOT NULL DEFAULT '',
      link_gitee TEXT NOT NULL DEFAULT '',
      link_live TEXT NOT NULL DEFAULT '',
      link_docs TEXT NOT NULL DEFAULT '',
      status TEXT NOT NULL DEFAULT 'active',
      status_label TEXT NOT NULL DEFAULT '进行中',
      is_featured BOOLEAN NOT NULL DEFAULT FALSE,
      sort INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS albums (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      description TEXT NOT NULL DEFAULT '',
      cover TEXT NOT NULL DEFAULT '',
      sort INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS photos (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      album_id BIGINT NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
      url TEXT NOT NULL,
      caption TEXT NOT NULL DEFAULT '',
      orientation TEXT NOT NULL DEFAULT 'landscape',
      sort INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS site_config (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      key TEXT NOT NULL UNIQUE,
      value TEXT NOT NULL DEFAULT '',
      description TEXT NOT NULL DEFAULT '',
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;

  await sql`CREATE INDEX IF NOT EXISTS posts_status_published_idx ON posts (status, published_at DESC)`;
  await sql`CREATE INDEX IF NOT EXISTS chatters_status_created_idx ON chatters (status, created_at DESC)`;
  await sql`CREATE INDEX IF NOT EXISTS projects_sort_idx ON projects (sort, created_at DESC)`;
  await sql`CREATE INDEX IF NOT EXISTS photos_album_sort_idx ON photos (album_id, sort, created_at DESC)`;
}
